/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.epdv.tools.configurator.httpd.ui;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

/**
 *
 * @author peter
 */
public class CfgEdListCellRenderer extends JPanel {

    private JComponent editorComponent;

    /**
     * Creates new form NewJPanel
     */
    public CfgEdListCellRenderer() {
        JComponent jc;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescription = new JLabel();
        jPanel1 = new JPanel();
        txtSettingName = new JLabel();

        setLayout(new BorderLayout(5, 8));

        Mnemonics.setLocalizedText(txtDescription, NbBundle.getMessage(CfgEdListCellRenderer.class, "CfgEdListCellRenderer.txtDescription.text")); // NOI18N
        add(txtDescription, BorderLayout.PAGE_START);

        jPanel1.setLayout(new BorderLayout(5, 8));

        Mnemonics.setLocalizedText(txtSettingName, NbBundle.getMessage(CfgEdListCellRenderer.class, "CfgEdListCellRenderer.txtSettingName.text")); // NOI18N
        txtSettingName.setVerticalAlignment(SwingConstants.TOP);
        jPanel1.add(txtSettingName, BorderLayout.LINE_START);

        add(jPanel1, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel jPanel1;
    private JLabel txtDescription;
    private JLabel txtSettingName;
    // End of variables declaration//GEN-END:variables
}
